api:
  base_url: "http://face_service:8000"
  api_key: "fs_9f2b8a71c4d04e5e9b3d8a7c6b5a4f3e" # Suggested secure key

sftp:
  api_path: "/webhookSFTPDirect" 
  host: "103.186.221.20"
  port: 2022 
  # list dir tmj 
  # port: 20022
  username: "fusion"
  password: "admin123"
  base_path: "/"
  poll_interval_sec: 60
  # processed_dirname: "processed"


external_api:
  enabled: false
  base_url: "https://live.thefusionapps.com"
  jwt_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJpZCI6MTAsInVzZXJOYW1lIjoiRnVzaW9uIFN1cHBvcnQiLCJ0ZW5hbnRJZCI6MTAsInJvbGUiOiJ0ZW5hbnQiLCJzbHVnIjoiYW5hbHl0aWNzIn0sImJyYW5jaERhdGEiOnsiaWQiOjUyLCJicmFuY2hJZCI6IlRNSi1DQkUifSwiaWF0IjoxNzc3NTI5MzgxLCJleHAiOjE3Nzc2MTU3ODF9.7INaT-cuBlPLFO6qi1a7SZJTY4PkSPErLjvsIx0Pk_c"
 
recognition:
  min_similarity: 0.60
  top_k: 6
  min_top2_margin: 0.12
  top2_high_conf_sim: 0.40


quality:
  min_blur: 50.0
  min_face_ratio: 0.05
  min_brightness: 28.0
  max_brightness: 220.0
  min_landmark_conf: 0.5
  max_abs_yaw: 70
  max_abs_pitch: 60
  min_resolution: 60

  
# POST /v1/events/recognition/forward this is forword api for send no match / match images 
# body 
# {
#   "event_id": "....",
#   "target_url": "https://your-api/endpoint"   // optional if FACE_SERVICE_FORWARD_URL is set
# }
# curl -X POST http://localhost:8001/v1/events/recognition/forward \
#   -H "Content-Type: application/json" \
#   -d '{"event_id":"<EVENT_ID>","target_url":"https://your-api/receive"}'

# Access web UI at http://localhost:6333/dashboard